[package]
name = "tlsglue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
rcgen = "0.13.1"
xdg = "2.5.2"
